import { Inter } from "next/font/google";

import "@/app/globals.css";
import MainFooter from "@/components/footer/main-footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
  icons: {
    icon: "icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" sizes="any" />
      </head>
      <body>
        <div>
          {/* <AuthProvider> */}
          <main>{children}</main>
          <MainFooter />
          {/* </AuthProvider> */}
        </div>
      </body>
    </html>
  );
}
