import Header from "@/components/header/header";
import { Inter } from "next/font/google";
import MobileHeader from "@/components/header/header-mobile";
import { CartProvider } from "@/context/cart-context";
import CartModal from "@/components/cart/cart-modal";
import "@/app/globals.css";
import MainFooter from "@/components/footer/main-footer";
import { Currency } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
  icons: {
    icon: "icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" sizes="any" />
      </head>
      <body>
        <div>
          <CartProvider>
            <main>{children}</main>
            <MainFooter />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
