import { Inter } from "next/font/google";

import "@/app/globals.css";
import MainFooter from "@/components/footer/main-footer";

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
  icons: {
    icon: "icon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ro">
      <head>
        <link rel="icon" href="/icon.png" sizes="any" />
      </head>
      <body>
        <main>{children}</main>
        <MainFooter />
      </body>
    </html>
  );
}
